param(
    [string]$Version
)

$ErrorActionPreference = 'Stop'

if (-not $Version) {
    $Version = $env:FOLDERVIEWER_VERSION
}

if (-not $Version) {
    $Version = (git describe --always --tags --dirty).Trim()
}

$numericMatch = [regex]::Match($Version, '\d+(?:\.\d+){0,3}')
$assemblyVersion = if ($numericMatch.Success) {
    $parts = @($numericMatch.Value.Split('.') | ForEach-Object { [int]$_ })
    while ($parts.Count -lt 4) { $parts += 0 }
    ($parts[0..3] -join '.')
} else {
    '0.0.0.0'
}

$text = @"
// This file is generated by update-version.ps1

using System.Reflection;

[assembly: AssemblyVersion("$assemblyVersion")]
[assembly: AssemblyInformationalVersion("$Version")]
"@

$text | Out-File $PSScriptRoot\..\GitVersion.cs -Encoding utf8

$xml = [xml](Get-Content $PSScriptRoot\..\QuickLook.Plugin.Metadata.Base.config)
$xml.Metadata.Version = $Version
$xml.Save("$PSScriptRoot\..\QuickLook.Plugin.Metadata.config")
